CREATE TABLE hotel_quotations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(100) NOT NULL,
  sys_id VARCHAR(100) NOT NULL,
  informations LONGTEXT NOT NULL,
  quotations LONGTEXT NULL,
  percentage DECIMAL(10,2) NULL,
  meta_data JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);